server:
  context-path: /
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/alleyz?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: aa122346
